### ISSUE TITLE
Need another way to map siren to BEAR.Resource?

### ISSUE THREAD

**Issue by kuma-guy** [kuma-guy/BEAR.SirenModule#4]
configure using YAML or XML file?

```
resources:
  order:
    get:
      class: 'order'
      embeds:
         resource: 
           rel:  [customer]
           src: app://self/customer{customerId}
```
